In [2]:
import torch
import numpy

In [6]:
# Создаем тензор
x = torch.rand([3, 4])
x = torch.zeros([3, 4])
x = torch.ones([3, 4, 3])

# print x
#x = torch.eye(3, 4)

x = torch.Tensor(
[[1,  2,  3,  4],
 [5,  6,  7,  8],
 [9, 10, 11, 12]])

print x, '<- tensor'
print x.size(), '<- tensor size'
print x.size(0), '<- dimension size'
print x[1:, 1:3], '<- slicing support'


  1   2   3   4
  5   6   7   8
  9  10  11  12
[torch.FloatTensor of size 3x4]
 <- tensor
torch.Size([3, 4]) <- tensor size
3 <- dimension size

  6   7
 10  11
[torch.FloatTensor of size 2x2]
 <- slicing support


In [7]:
# Копирование (по ссылке и глубокое)
y = x

y[1, :] = 1
print x, y, '<- shallow copy'

y = x.clone()
y[1, :] = 2
print x, y, '<- deep copy'


  1   2   3   4
  1   1   1   1
  9  10  11  12
[torch.FloatTensor of size 3x4]
 
  1   2   3   4
  1   1   1   1
  9  10  11  12
[torch.FloatTensor of size 3x4]
 <- shallow copy

  1   2   3   4
  1   1   1   1
  9  10  11  12
[torch.FloatTensor of size 3x4]
 
  1   2   3   4
  2   2   2   2
  9  10  11  12
[torch.FloatTensor of size 3x4]
 <- deep copy


In [10]:
# Математические операции (стандартные поэлементные)
print x + y, x * y, x / y, x - y, 
print x % y, x**2, x**y, '<- basic math'


  2   4   6   8
  3   3   3   3
 18  20  22  24
[torch.FloatTensor of size 3x4]
 
   1    4    9   16
   2    2    2    2
  81  100  121  144
[torch.FloatTensor of size 3x4]
 
 1.0000  1.0000  1.0000  1.0000
 0.5000  0.5000  0.5000  0.5000
 1.0000  1.0000  1.0000  1.0000
[torch.FloatTensor of size 3x4]
 
 0  0  0  0
-1 -1 -1 -1
 0  0  0  0
[torch.FloatTensor of size 3x4]
 
 0  0  0  0
 1  1  1  1
 0  0  0  0
[torch.FloatTensor of size 3x4]
 
   1    4    9   16
   1    1    1    1
  81  100  121  144
[torch.FloatTensor of size 3x4]
 
 1.0000e+00  4.0000e+00  2.7000e+01  2.5600e+02
 1.0000e+00  1.0000e+00  1.0000e+00  1.0000e+00
 3.8742e+08  1.0000e+10  2.8531e+11  8.9161e+12
[torch.FloatTensor of size 3x4]
 <- basic math
484.0


In [38]:
# Более сложные операции
print torch.exp(x)
print torch.log(x)
print torch.sin(x)


 2.7183e+00  7.3891e+00  2.0086e+01  5.4598e+01
 2.7183e+00  2.7183e+00  2.7183e+00  2.7183e+00
 8.1031e+03  2.2026e+04  5.9874e+04  1.6275e+05
[torch.FloatTensor of size 3x4]


 0.0000  0.6931  1.0986  1.3863
 0.0000  0.0000  0.0000  0.0000
 2.1972  2.3026  2.3979  2.4849
[torch.FloatTensor of size 3x4]


 0.8415  0.9093  0.1411 -0.7568
 0.8415  0.8415  0.8415  0.8415
 0.4121 -0.5440 -1.0000 -0.5366
[torch.FloatTensor of size 3x4]



In [49]:
# Логические операции
y = x[x > 3]
print(y)
y = (x > 3)
print(y)


  4
  9
 10
 11
 12
[torch.FloatTensor of size 5]


 0  0  0  1
 0  0  0  0
 1  1  1  1
[torch.ByteTensor of size 3x4]



In [54]:
# Переопределение типа
x = x.float()
print x
x = x.double()
print x
x = x.int()
print(x)
x = x.float()


  1   2   3   4
  1   1   1   1
  9  10  11  12
[torch.cuda.FloatTensor of size 3x4 (GPU 0)]


  1   2   3   4
  1   1   1   1
  9  10  11  12
[torch.cuda.DoubleTensor of size 3x4 (GPU 0)]


  1   2   3   4
  1   1   1   1
  9  10  11  12
[torch.cuda.IntTensor of size 3x4 (GPU 0)]



In [71]:
# Взаимодействие с Numpy
x = numpy.array([[1, 2, 3, 4], [4, 3, 2, 1]])
print x
x = torch.from_numpy(x)
print x
x = x.numpy()
print x
x = torch.from_numpy(x).float().int().double()

[[1 2 3 4]
 [4 3 2 1]]

 1  2  3  4
 4  3  2  1
[torch.LongTensor of size 2x4]

[[1 2 3 4]
 [4 3 2 1]]


In [11]:
# Перемещение на GPU
import time
x_cuda = x.cuda()
print x_cuda, '<- CUDA Tensor!'
print x
start = time.time()
y = (x - x + x*10.0) ** 2
print time.time() - start, '<- CPU time'
start = time.time()
y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2
print time.time() - start, '<- GPU time' 
y = y_cuda.cpu()
print y
# print(x ** 2, '<- operation performed on the GPU!!!')
# print x = 


  1   2   3   4
  1   1   1   1
  9  10  11  12
[torch.cuda.FloatTensor of size 3x4 (GPU 0)]
 <- CUDA Tensor!

  1   2   3   4
  1   1   1   1
  9  10  11  12
[torch.FloatTensor of size 3x4]

0.000806093215942 <- CPU time
0.00588822364807 <- GPU time

   100.0000    400.0000    899.9999   1600.0000
   100.0000    100.0000    100.0000    100.0000
  8100.0000  10000.0010  12100.0010  14399.9990
[torch.FloatTensor of size 3x4]



In [15]:
# Автоматическое (символьное) дифференциирование (обратное распространение градиента) (случай скаляра)
import torch.autograd
print x
x_var = torch.autograd.Variable(x, requires_grad=True)
formula = (x_var ** 2).sum()
formula.backward()

print x_var.grad, '<- gradient'


  1   2   3   4
  1   1   1   1
  9  10  11  12
[torch.FloatTensor of size 3x4]

Variable containing:
  2   4   6   8
  2   2   2   2
 18  20  22  24
[torch.FloatTensor of size 3x4]
 <- gradient


In [127]:
# Автоматическое дифференциирование (обратное распространение градиента) (случай тензора)
# variable -> formula1 (вектор) -> formula2 (скаляр)
x_var = torch.autograd.Variable(x, requires_grad=True)
formula1 = torch.exp(x_var) ** 2.0
y_var = torch.autograd.Variable(formula1.data.clone(), requires_grad=True)
formula2 = y_var.sum()
formula2.backward()
y_grad = y_var.grad.clone()
print formula1
print y_grad
formula1.backward(gradient=y_grad.data)
print x_var.grad

Variable containing:
    7.3891    54.5982   403.4288  2980.9578
 2980.9578   403.4288    54.5982     7.3891
[torch.FloatTensor of size 2x4]

Variable containing:
 1  1  1  1
 1  1  1  1
[torch.FloatTensor of size 2x4]

Variable containing:
   14.7781   109.1963   806.8576  5961.9155
 5961.9155   806.8576   109.1963    14.7781
[torch.FloatTensor of size 2x4]



## Задание 1
Написать и вычислить бинарную кросс-энтопию для векторов target и probs при помощи средств pytorch.
Бинарная кросс-энтропия вычисляется:

$$BCE(t, p) = - \sum_i t_i \log(p_i) + (1 - t_i) \log(1 - p_i)$$

target = (0, 0, 0, 0, 1, 1, 1, 1)
probs = (0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8)

Какой из элементов суммы дает наибольший вклад в функцию потерь?

# Задание 2

Логистическая регрессия минимизирует функцию бинарная кросс-энтропия BCE, предполагая, что
$$p_i = \sigma (< w_i, x_i >)$$
где $w_i$ -- веса свойств объектов, $x_i$ -- свойства объектов. Пусть $\vec{x} = (1, x_1, x_2)$. Подставить вероятности в выражение $BCE$ и найти производную $BCE$ по весам.
Вычислить производную в случае двух объектов (любым способом, можно посчитать руками, можно написать скрипт):

$t = 1, x = (1, 1, 1)$
$t = 0, x = (1, 0, 1)$

В точке w = (0, 0, 0).

Совпадает ли результат явного вычисления с результатом работы функции backward?

## Задание 3

Средствами pytorch реализовать алгоритм градиентного спуска.

При помощи этого алгоритма найти минимум функций:
$x^2 + y^2$ с начальным приближением $x_0 = 10, y_0 = 5$, 

$0.5 \log x + 0.5 \log (1 - x)$ с начальным приближением $x_0 = 0.9$, 

$x^2 + 10 y^2 + 2xy$, с начальным приближением $x_0 = 10.0, y_0 = 10.0$

## Задание 4


При помощи алгоритма градиентного спуска оптимизировать вектор probs при фиксированном векторе target из задания 1.
Рассмотреть два варианта решения задачи: 

1) при помощи CPU 

2) при помощи GPU

Получилось ли ускорить процесс при помощи GPU? Обсудить, почему.

О градиентном спуске:
https://ru.wikipedia.org/wiki/%D0%93%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%81%D0%BA