In [6]:
import torch
import numpy

In [7]:
# Создаем тензор
x = torch.rand([3, 4])
x = torch.zeros([3, 4])
x = torch.ones([3, 4, 3])

# print x
#x = torch.eye(3, 4)

x = torch.Tensor(
[[1,  2,  3,  4],
 [5,  6,  7,  8],
 [9, 10, 11, 12]])

print(x, '<- tensor\n')
print(x.size(), '<- tensor size\n')
print(x.size(0), '<- dimension size\n')
print(x[1:, 1:3], '<- slicing support\n')

tensor([[  1.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]]) <- tensor

torch.Size([3, 4]) <- tensor size

3 <- dimension size

tensor([[  6.,   7.],
        [ 10.,  11.]]) <- slicing support



In [10]:
# Копирование (по ссылке и глубокое)
y = x

y[1, :] = 1
print(x, '\n', y, '<- shallow copy\n')

y = x.clone()
y[1, :] = 2
print(x, '\n', y, '<- deep copy')

tensor([[  1.,   2.,   3.,   4.],
        [  1.,   1.,   1.,   1.],
        [  9.,  10.,  11.,  12.]]) 
 tensor([[  1.,   2.,   3.,   4.],
        [  1.,   1.,   1.,   1.],
        [  9.,  10.,  11.,  12.]]) <- shallow copy

tensor([[  1.,   2.,   3.,   4.],
        [  1.,   1.,   1.,   1.],
        [  9.,  10.,  11.,  12.]]) 
 tensor([[  1.,   2.,   3.,   4.],
        [  2.,   2.,   2.,   2.],
        [  9.,  10.,  11.,  12.]]) <- deep copy


In [11]:
# Математические операции (стандартные поэлементные)
print(x + y, x * y, x / y, x - y,)
print(x % y, x**2, x**y, '<- basic math')

tensor([[  2.,   4.,   6.,   8.],
        [  3.,   3.,   3.,   3.],
        [ 18.,  20.,  22.,  24.]]) tensor([[   1.,    4.,    9.,   16.],
        [   2.,    2.,    2.,    2.],
        [  81.,  100.,  121.,  144.]]) tensor([[ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 0.5000,  0.5000,  0.5000,  0.5000],
        [ 1.0000,  1.0000,  1.0000,  1.0000]]) tensor([[ 0.,  0.,  0.,  0.],
        [-1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.]])
tensor([[ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.]]) tensor([[   1.,    4.,    9.,   16.],
        [   1.,    1.,    1.,    1.],
        [  81.,  100.,  121.,  144.]]) tensor([[ 1.0000e+00,  4.0000e+00,  2.7000e+01,  2.5600e+02],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 3.8742e+08,  1.0000e+10,  2.8531e+11,  8.9161e+12]]) <- basic math


In [12]:
# Более сложные операции
print(torch.exp(x))
print(torch.log(x))
print(torch.sin(x))

tensor([[ 2.7183e+00,  7.3891e+00,  2.0086e+01,  5.4598e+01],
        [ 2.7183e+00,  2.7183e+00,  2.7183e+00,  2.7183e+00],
        [ 8.1031e+03,  2.2026e+04,  5.9874e+04,  1.6275e+05]])
tensor([[ 0.0000,  0.6931,  1.0986,  1.3863],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 2.1972,  2.3026,  2.3979,  2.4849]])
tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [ 0.8415,  0.8415,  0.8415,  0.8415],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])


In [13]:
# Логические операции
y = x[x > 3]
print(y)
y = (x > 3)
print(y)

tensor([  4.,   9.,  10.,  11.,  12.])
tensor([[ 0,  0,  0,  1],
        [ 0,  0,  0,  0],
        [ 1,  1,  1,  1]], dtype=torch.uint8)


In [14]:
# Переопределение типа
x = x.float()
print(x)
x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()

tensor([[  1.,   2.,   3.,   4.],
        [  1.,   1.,   1.,   1.],
        [  9.,  10.,  11.,  12.]])
tensor([[  1.,   2.,   3.,   4.],
        [  1.,   1.,   1.,   1.],
        [  9.,  10.,  11.,  12.]], dtype=torch.float64)
tensor([[  1,   2,   3,   4],
        [  1,   1,   1,   1],
        [  9,  10,  11,  12]], dtype=torch.int32)


In [15]:
# Взаимодействие с Numpy
x = numpy.array([[1, 2, 3, 4], [4, 3, 2, 1]])
print(x)
x = torch.from_numpy(x)
print(x)
x = x.numpy()
print(x)
x = torch.from_numpy(x).float().int().double()
print(x)

[[1 2 3 4]
 [4 3 2 1]]
tensor([[ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])
[[1 2 3 4]
 [4 3 2 1]]
tensor([[ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=torch.float64)


In [107]:
# Перемещение на GPU
import time
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device, 'is avaliable')
x_cuda = x.to('cuda:0')
print(x_cuda, '<- CUDA Tensor!')
print(x)

In [105]:
# CPU time
%time y = (x - x + x*10.0) ** 2

CPU times: user 774 µs, sys: 598 µs, total: 1.37 ms
Wall time: 819 µs


In [108]:
# GPU time
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

In [21]:
# Автоматическое (символьное) дифференциирование (обратное распространение градиента) (случай скаляра)
import torch.autograd

x = torch.tensor(
    [[1,  2,  3,  4],
     [5,  6,  7,  8],
     [9, 10, 11, 12]], requires_grad=True)

formula = (x ** 2).sum().median()
formula.backward()

print(x.grad, '<- gradient')

tensor([[  2,   4,   6,   8],
        [ 10,  12,  14,  16],
        [ 18,  20,  22,  24]]) <- gradient


In [86]:
# Как тензор хранит свою историю
print(formula.grad_fn)
print(formula.grad_fn.next_functions[0][0])
print(formula.grad_fn.next_functions[0][0].next_functions[0][0])
print(formula.grad_fn.next_functions[0][0].next_functions[0][0].next_functions[0][0])

## Задание 1
Написать и вычислить бинарную кросс-энтопию для векторов target и probs при помощи средств pytorch.
Бинарная кросс-энтропия вычисляется:

$$BCE(t, p) = - \sum_i t_i \log(p_i) + (1 - t_i) \log(1 - p_i)$$

target = (0, 0, 0, 0, 1, 1, 1, 1)
probs = (0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8)

Какой из элементов суммы дает наибольший вклад в функцию потерь?

# Задание 2

Логистическая регрессия минимизирует функцию бинарной кросс-энтропии (BCE), предполагая, что
$$p_i = \sigma (< w_i, x_i >)$$
где $w_i$ -- веса свойств объектов, $x_i$ -- свойства объектов. Пусть $\vec{x} = (1, x_1, x_2)$. Подставить вероятности в выражение $BCE$ и найти производную $BCE$ по весам.
Вычислить производную в случае двух объектов (любым способом, можно посчитать руками, можно написать скрипт):

$t = 1, x = (1, 1, 1)$

$t = 0, x = (1, 0, 1)$

В точке w = (0, 0, 0).

Совпадает ли результат явного вычисления с результатом работы функции backward?

## Задание 3

Средствами pytorch реализовать алгоритм градиентного спуска.

При помощи этого алгоритма найти минимум функций:
$x^2 + y^2$ с начальным приближением $x_0 = 10, y_0 = 5$, 

$0.5 \log x + 0.5 \log (1 - x)$ с начальным приближением $x_0 = 0.9$, 

$x^2 + 10 y^2 + 2xy$, с начальным приближением $x_0 = 10.0, y_0 = 10.0$

## Задание 4


При помощи алгоритма градиентного спуска оптимизировать вектор probs при фиксированном векторе target из задания 1.
Рассмотреть два варианта решения задачи: 

1) при помощи CPU 

2) при помощи GPU

Получилось ли ускорить процесс при помощи GPU? Обсудить, почему.

О градиентном спуске:
https://ru.wikipedia.org/wiki/%D0%93%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%81%D0%BA