### Основные функции

In [5]:
import torch
import torchvision
import numpy

In [6]:
x = torch.Tensor(5, 3) # Создаем тензор (просто выделяем память)

In [7]:
print(x) # Можно посмотреть, что в тензоре


1.00000e-09 *
 -1.8976  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
[torch.FloatTensor of size 5x3]



In [8]:
x = torch.rand(5, 3) # Тензор со случайными числами между 1 и 0
print(x)


 0.5697  0.6963  0.3337
 0.3358  0.4933  0.9774
 0.8188  0.1457  0.6445
 0.3764  0.5083  0.4676
 0.1340  0.0563  0.2282
[torch.FloatTensor of size 5x3]



In [9]:
y = torch.ones(5, 3) # Создаем тензор из единиц
print(x + y) # Тензоры можно складывать!!!


 1.5697  1.6963  1.3337
 1.3358  1.4933  1.9774
 1.8188  1.1457  1.6445
 1.3764  1.5083  1.4676
 1.1340  1.0563  1.2282
[torch.FloatTensor of size 5x3]



In [11]:
print(x * y) # И умножать...


 0.5697  0.6963  0.3337
 0.3358  0.4933  0.9774
 0.8188  0.1457  0.6445
 0.3764  0.5083  0.4676
 0.1340  0.0563  0.2282
[torch.FloatTensor of size 5x3]



In [12]:
y.add_(x) # In-place операции
print(y)


 1.5697  1.6963  1.3337
 1.3358  1.4933  1.9774
 1.8188  1.1457  1.6445
 1.3764  1.5083  1.4676
 1.1340  1.0563  1.2282
[torch.FloatTensor of size 5x3]



In [13]:
print(x[:, 1]) # Можно делать слайсы


 0.6963
 0.4933
 0.1457
 0.5083
 0.0563
[torch.FloatTensor of size 5]



In [14]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [16]:
b = a.numpy() # Перегнать в numpy просто
print(b)

[ 1.  1.  1.  1.  1.]


In [17]:
a.add_(1) # На самом деле, numpy и torch используют одну и ту же память
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) # Можно перегонять из numpy в torch
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [20]:
if torch.cuda.is_available(): # Можно проверить, есть ли CUDA на тачке
    x = x.cuda() # перемещаем x на графкарту
    y = y.cuda()
    x + y        # на графкарте
    
    x = x.cpu()  # на процессор

### Autograd

In [21]:
import torch
from torch.autograd import Variable

In [22]:
x = Variable(torch.ones(2, 2), requires_grad=True) # Создаем переменную
print(x)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [23]:
y = x + 2 # Делаем операции
print(y)

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]



In [31]:
print(y.grad_fn) # У переменной теперь есть grad_fn

In [32]:
z = y * y * 3
out = z.mean() # Можно делать много операций, НО нельзя перезаписывать

print(z, out)

Variable containing:
1.00000e+06 *
  0.3022
  0.0005
  3.4533
[torch.FloatTensor of size 3]
 Variable containing:
1.00000e+06 *
  1.2520
[torch.FloatTensor of size 1]



In [26]:
out.backward() # МАГИЯ!!!

In [27]:
print(x.grad) # И теперь везде посчитаны градиенты

Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]



In [29]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

Variable containing:
 -317.3658
  -12.5525
-1072.8895
[torch.FloatTensor of size 3]



In [30]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)

print(x.grad)

Variable containing:
  51.2000
 512.0000
   0.0512
[torch.FloatTensor of size 3]

